branches:
 only:
  - master
  - /^develop.*$/
dist: bionic

services:
  - docker

script:
  - docker run -t -v $PWD:/proSU dirack/ambienteprosu:1.2 bash -c 'CWPROOT=$HOME && PATH=$PATH:$CWPROOT/bin && make test'

